export const FETCH_CENTRENAME = 'ADD_CENTRENAME'
export const FETCH_CENTRENAME_PENDING = 'FETCH_CENTRENAME_PENDING'
export const FETCH_CENTRENAME_SUCCESS = 'FETCH_CENTRENAME_SUCCESS'
export const FETCH_CENTRENAME_ERROR = 'FETCH_CENTRENAME_ERROR'

export const FETCH_CENTREPARAMS = 'FETCH_CENTREPARAMS'
export const FETCH_CENTREPARAMS_PENDING = 'FETCH_CENTRENAME_PENDING'
export const FETCH_CENTREPARAMS_SUCCESS = 'FETCH_CENTRENAME_SUCCESS'
export const FETCH_CENTREPARAMS_ERROR = 'FETCH_CENTRENAME_ERROR'
